### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by wangxp2016** [jflyfox/jfinal_cms#1]
java.lang.NoClassDefFoundError: com/mchange/v2/c3p0/ComboPooledDataSource

**Comment by zcool321** [comment]
bulid maven project. need maven install

**Comment by frandfeng** [comment]
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
java.sql.SQLException: Connections could not be acquired from the underlying database!
maven启动tomcat的时候出现这个，我的用户名和密码，数据库这些配置都是正确的

**Comment by zcool321** [comment]
这个是数据库权限问题~应该你是的项目没有编译成功还是使用的默认配置导致的~
请重新进行clean然后maven isntall
