### ISSUE TITLE
Regex sanitizer bypass to arbitrary file read and directory traversal

### ISSUE THREAD

**Issue by ztz472947849** [jflyfox/jfinal_cms#11]
admin login required.

FileManager.java
```java
	private String sanitize(String var) {
		String sanitized = var.replaceAll("\\<.*?>", "");
		sanitized = sanitized.replaceAll("http://", "");
		sanitized = sanitized.replaceAll("https://", "");
		sanitized = sanitized.replaceAll("\\.\\./", "");
		return sanitized;
	}
```

regex expression "\\.\\./" is designed to filter out "../" while "..././" totally bypasses it. it leads to arbitrary file read and directory traversal using admin portal's file manager.

"../" won't work
![image](https://user-images.githubusercontent.com/5858458/55562111-e7732400-5725-11e9-9279-40175fe477c1.png)

"..././" works.
![image](https://user-images.githubusercontent.com/5858458/55562223-15586880-5726-11e9-9070-55700f106e88.png)

**Comment by zcool321** [comment]
已处理，下一版本更新
