### ISSUE TITLE
SQL injection in user role listing

### ISSUE THREAD

**Issue by ztz472947849** [jflyfox/jfinal_cms#12]
admin login required.

RoleController.java
```java
public void list() {
		SysRole model = getModelByAttr(SysRole.class);

		SQLUtils sql = new SQLUtils(" from sys_role t where 1=1 ");
		if (model.getAttrValues().length != 0) {
			sql.setAlias("t");
			// 查询条件
			sql.whereLike("name", model.getStr("name"));
		}
```
SQLUtils.java
```java
	public void whereLike(String attrName, String value) {
		if (StrUtils.isNotEmpty(value)) {
			sqlBuffer.append(" AND " + getAttrName(attrName) + " LIKE '%").append(value).append("%'");
		}
	}
```
query here doesn't go through ORM nor data binding procedures.
full error msg appears in response too.

most queries DO go through data binding procedures.
![image](https://user-images.githubusercontent.com/5858458/55565145-e34a0500-572b-11e9-8d32-e65d440cfac6.png)
The whereLike implementation is vulnerable to SQL injection.
![image](https://user-images.githubusercontent.com/5858458/56858025-a37ee200-69a6-11e9-88e0-b9b120770c2b.png)
![image](https://user-images.githubusercontent.com/5858458/55565210-007ed380-572c-11e9-80fb-15f7f0927f9d.png)

EDIT: add more detail

**Comment by zcool321** [comment]
已处理，下版本更新
