### ISSUE TITLE
A Stored XSS vulnerability exists in jfinal_cms v5.1.0

### ISSUE THREAD

**Issue by Al1ex** [jflyfox/jfinal_cms#18]
There is a storage XSS vulnerability in the blog post of jfinal_ CMS. An attacker can register an account first, then insert malicious XSS code in the post post, and then successfully trigger XSS attack when the administrator or other users view the post.
First, register a user test, publish the blog, and insert the malicious XSS attack code in the title of the blog post:
Payload：
`test<img src=x oneerror=alert(document.cookie);>`
![image](https://user-images.githubusercontent.com/38161463/83646470-419b9d80-a5e6-11ea-8622-4e609801e263.png)
XSS code can be triggered successfully when viewing the blog post
![image](https://user-images.githubusercontent.com/38161463/83646628-7c9dd100-a5e6-11ea-94b8-e4111c073c9e.png)
![image](https://user-images.githubusercontent.com/38161463/83646634-80315800-a5e6-11ea-8721-3b2e1cbd00ca.png)
Because the blog is visible to any user, XSS code can be triggered when any other user views the blog. Here is an example of viewing the blog as an administrator:
![image](https://user-images.githubusercontent.com/38161463/83646690-93442800-a5e6-11ea-9094-ec02497246bd.png)
XSS code triggered successfully:
![image](https://user-images.githubusercontent.com/38161463/83646799-be2e7c00-a5e6-11ea-9646-58dfc625d8ae.png)

Suggestion: strictly filter the input and code the output

**Comment by zcool321** [comment]
fixed
