### ISSUE TITLE
A Stored XSS vulnerability exists in jfinal_cms v5.1.0

### ISSUE THREAD

**Issue by Al1ex** [jflyfox/jfinal_cms#19]
There is a storage XSS vulnerability in the modification of jfinal_CMS user's personal information. The attacker can insert malicious XSS code into the modification of personal information, and then successfully trigger XSS attack when the administrator user views the user's personal information.
First, register a user test, then enter the personal information page, insert the malicious XSS attack code in the remarks:
payload:
`"><img src=x onerror=alert(document.cookie);><"`
![image](https://user-images.githubusercontent.com/38161463/83648691-ed45ed00-a5e8-11ea-97dc-73ad0ef6701c.png)
Then use the administrator account to view the user information:
![image](https://user-images.githubusercontent.com/38161463/83648793-10709c80-a5e9-11ea-9ebe-3d89fe74520c.png)
Successfully triggered malicious XSS Code:
![image](https://user-images.githubusercontent.com/38161463/83648860-21b9a900-a5e9-11ea-9491-da5c57b8c670.png)

Safety advice: strictly filter the user's input

**Comment by zcool321** [comment]
same #18
