### ISSUE TITLE
Unsanitized comments causing a stored XSS vulnerability 

### ISSUE THREAD

**Issue by ztz472947849** [jflyfox/jfinal_cms#8]
Navigate to any post and make comment (login required) as below `</span><svg/onload=alert('xss')>`
Refresh that page and users will be popped with an `alert()` dialogue.

![image](https://user-images.githubusercontent.com/5858458/55524585-70577480-56c0-11e9-9f55-840eb21bf2f2.png)
![image](https://user-images.githubusercontent.com/5858458/55524605-7fd6bd80-56c0-11e9-8820-d86cac2dc16c.png)
![image](https://user-images.githubusercontent.com/5858458/55524614-8a915280-56c0-11e9-9290-54f9276359eb.png)

http://mtg.jflyfox.com/front/article/4615.html

**Comment by zcool321** [comment]
下一版本解决
